services:
  mongo:
    image: mongo:7
    container_name: taskmanager-mongo
    restart: always
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./server
    container_name: taskmanager-backend
    restart: always
    environment:
      NODE_ENV: "production"
      MONGO_URI: mongodb://mongo:27017/taskdb
      PORT: 5000
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  frontend:
    build:
      context: ./client
    container_name: taskmanager-frontend
    restart: always
    ports:
      - "3000:80"   # Serve built React app
    depends_on:
      - backend

volumes:
  mongo_data:
